language: node_js
node_js:
  - 12
notifications:
  email: false

script:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run ci-deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run ci-tagged-deploy
    on:
      tags: true
