language: node_js
node_js:
  - 12
notifications:
  email: false
before_install:
  - echo "//npm.pkg.github.com/:_authToken=\${GITHUB_REGISTRY_TOKEN}" > ~/.npmrc
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./build
  fqdn: airglow.moon.moe
  email: bot@moon.moe
  on:
    branch: master
