language: node_js
node_js:
  - 12
notifications:
  email: false

before_install:
  - echo "//npm.pkg.github.com/:_authToken=\${GITHUB_REGISTRY_TOKEN}" >> ~/.npmrc

script:
  - npm run build

before_deploy:
  - ./scripts/ci-prepare.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run ci-deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run ci-tagged-deploy
    on:
      tags: true
